# Generated by Django 6.0 on 2025-12-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_name', models.CharField(max_length=100)),
                ('seller_place', models.CharField(max_length=100)),
                ('seller_phno', models.CharField(max_length=15)),
            ],
        ),
    ]
