# Generated by Django 6.0 on 2025-12-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
