# Generated by Django 6.0 on 2025-12-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_purchase_purchase_total_sales_sales_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10000),
        ),
    ]
